### ISSUE TITLE
Unable to play video in Kodi 19

### ISSUE THREAD

**Issue by JayXon** [plexinc/plex-for-kodi#346]
## Description:
After updated to 0.3.2, I can finally launch plex, but after hitting play video, it just stuck there with video art background.

## Details:
- Add-on version: 0.3.2
- Kodi version: 19
- OS Platform: Android TV
- Hardware: Shield

## Checklist
- [x] I have included a link to a log (or at the very least a link to a forum post with a log) from a session that had the issue
- [ ] I have added appropriate GitHub labels
It doesn't look like I have permission to add labels

```
2021-02-19 21:45:30.383 T:10423   ERROR <general>: script.plex: ERROR:
2021-02-19 21:45:30.383 T:10423   ERROR <general>:     Traceback (most recent call last):
2021-02-19 21:45:30.383 T:10423   ERROR <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/settings.py", line 133, in valueLabel
2021-02-19 21:45:30.383 T:10423   ERROR <general>:         dist = platform. dist()
2021-02-19 21:45:30.384 T:10423   ERROR <general>:     AttributeError: module 'platform' has no attribute 'dist'
2021-02-19 21:45:30.384 T:10423   ERROR <general>: _________________________________________________________________________________
2021-02-19 21:45:30.384 T:10423   ERROR <general>: `
2021-02-19 21:45:30.385 T:10423   ERROR <general>: _________________________________________________________________________________
2021-02-19 21:45:30.385 T:10423   ERROR <general>: script.plex: ERROR:
2021-02-19 21:45:30.385 T:10423   ERROR <general>:     Traceback (most recent call last):
2021-02-19 21:45:30.385 T:10423   ERROR <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/settings.py", line 297, in onAction
2021-02-19 21:45:30.385 T:10423   ERROR <general>:         self.checkSection()
2021-02-19 21:45:30.385 T:10423   ERROR <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/settings.py", line 334, in checkSection
2021-02-19 21:45:30.385 T:10423   ERROR <general>:         self.showSettings(self.lastSection)
2021-02-19 21:45:30.386 T:10423   ERROR <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/settings.py", line 354, in showSettings
2021-02-19 21:45:30.386 T:10423   ERROR <general>:         item = kodigui.ManagedListItem(setting.label, setting.type != 'BOOL' and setting.valueLabel() or '', data_source=setting)
2021-02-19 21:45:30.386 T:10423   ERROR <general>:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/settings.py", line 142, in valueLabel
2021-02-19 21:45:30.386 T:10423   ERROR <general>:         plat = plat.strip()
2021-02-19 21:45:30.386 T:10423   ERROR <general>:     UnboundLocalError: local variable 'plat' referenced before assignment
2021-02-19 21:45:30.386 T:10423   ERROR <general>: _________________________________________________________________________________
2021-02-19 21:45:30.386 T:10423   ERROR <general>: `
2021-02-19 21:45:41.064 T:10310    INFO <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-episodes.xml, load type: LOAD_ON_GUI_INIT
2021-02-19 21:45:41.216 T:10310    INFO <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-busy.xml, load type: LOAD_ON_GUI_INIT
2021-02-19 21:45:49.621 T:10310    INFO <general>: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/resources/skins/Main/1080i/script-plex-video_player.xml, load type: LOAD_ON_GUI_INIT
2021-02-19 21:45:50.066 T:10423   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/kodigui.py", line 105, in onInit
                                                       self.onFirstInit()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/videoplayer.py", line 91, in onFirstInit
                                                       self.play(resume=self.resume)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/videoplayer.py", line 234, in play
                                                       player.PLAYER.playVideoPlaylist(self.playQueue, resume=self.resume, session_id=id(self), handler=handler)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/player.py", line 806, in playVideoPlaylist
                                                       self._playVideo(resume and self.video.viewOffset.asInt() or 0, seeking=handler and handler.SEEK_PLAYLIST or 0, force_update=True)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/player.py", line 761, in _playVideo
                                                       self.handler.setup(self.video.duration.asInt(), offset, bifURL, title=self.video.grandparentTitle, title2=self.video.title, seeking=seeking)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/player.py", line 169, in setup
                                                       self.getDialog(setup=True)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/player.py", line 174, in getDialog
                                                       self.dialog = seekdialog.SeekDialog.create(show=False, handler=self)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/kodigui.py", line 44, in create
                                                       window = cls(cls.xmlFile, cls.path, cls.theme, cls.res, **kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/windows/seekdialog.py", line 123, in __init__
                                                       self.intro = self.handler.player.video.intro
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/_included_packages/plexnet/video.py", line 461, in intro
                                                       self._intro = list((filter(lambda x: x.type == "intro", self.markers) or [False]))[0]
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
```

**Comment by Rootax** [comment]
Same behavior here : /

**Comment by pun-private** [comment]
it seems that the addon was written for python 2 and kodi 19 runs only python3 addons...

**Comment by Rootax** [comment]
The 3.x version support python3 I believe (2.x is for python 2).

Le dim. 21 févr. 2021 à 18:33, pun-private <notifications@github.com> a
écrit :

**Comment by curiexr** [comment]
Same issue here. Can't play videos on Kodi 19. Any upcoming updates to this addon?

**Comment by ruuk** [comment]
Fixed and submitted to Kodi repo.

**Comment by Generator** [comment]
This issue is still present on Kodi19 with PlexForKodi 0.3.3.  

When press play it takes about almost 1 minute to play the video.

**Comment by ruuk** [comment]
If you're able to play the video, this is not the same issue. Please create a new issue with details about your setup, etc.
